[project]
name = "email_organizer"
version = "0.0.1"
description = "Organize emails based off user's email"
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[crewai]>=0.3.4",
]