assign_labels:
  description: >-
    Analyze the {emails.json} and organize them based off the given parameters: work, school,
    spam/promotion, miscellaneous
  expected_output: >-
    Return a text file of the organized emails with their respective ID in this format, ID: label.
    Before you begin the list, please write "START OF OUTPUT" and then a new line
    Please format the output in this manner:
      ID: label,
      ID: label,
      ID: label,
      ID: label,
      .
      .
      .
    Please indent after each comma to a new line.
    At the end, please end the list with "END OF OUTPUT" with a newline as well.
  agent: >-
    organize_emails
  variables:
    EMAILS: "emails.json"